import type { Metadata } from 'next';
import { JSX } from 'react';

import {
    ClerkProvider,
} from '@clerk/nextjs';
import { Geist, Geist_Mono , NextFontWithVariable } from 'next/font/google';
import './globals.css';



const geistSans: NextFontWithVariable = Geist({
    variable: '--font-geist-sans',
    subsets: [ 'latin' ],
});

const geistMono : NextFontWithVariable = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: [ 'latin' ],
});

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode
}>):JSX.Element {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
